version: '3.3'
services:

  db_order_service:
    image: postgres:latest
    restart: always
    ports:
      - ${ORDER_POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${ORDER_POSTGRES_USER}
      - POSTGRES_PASSWORD=${ORDER_POSTGRES_PASSWORD}
      - POSTGRES_DB=${ORDER_POSTGRES_DB}
    depends_on:
      - discovery
  db_product_service:
    image: postgres:latest
    restart: always
    ports:
      - ${PRODUCT_POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${PRODUCT_POSTGRES_USER}
      - POSTGRES_PASSWORD=${PRODUCT_POSTGRES_PASSWORD}
      - POSTGRES_DB=${PRODUCT_POSTGRES_DB}
    depends_on:
      - discovery
  order_service:
    build:
      dockerfile: order-DockerFile
    ports:
      - ${ORDER_SERVER_PORT}:8081
    depends_on:
      - db_order_service
      - discovery
    environment:
      ORDER_DATASOURCE_URL: jdbc:postgresql://db_order_service:5432/${ORDER_POSTGRES_DB}
      ORDER_DATASOURCE_USERNAME: ${ORDER_POSTGRES_USER}
      ORDER_DATASOURCE_PASSWORD: ${ORDER_POSTGRES_PASSWORD}
      #EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://discovery:8761/eureka
      eureka.client.service-url.defaultZone: http://discovery:8761/eureka
    links:
      - discovery
      - db_order_service
  product_service:
    build:
      dockerfile: product-DockerFile
    ports:
      - ${PRODUCT_SERVER_PORT}:8082
    depends_on:
      - db_product_service
      - discovery
    environment:
      PRODUCT_DATASOURCE_URL: jdbc:postgresql://db_product_service:5432/${PRODUCT_POSTGRES_DB}
      PRODUCT_DATASOURCE_USERNAME: ${PRODUCT_POSTGRES_USER}
      PRODUCT_DATASOURCE_PASSWORD: ${PRODUCT_POSTGRES_PASSWORD}
      eureka.client.service-url.defaultZone: http://discovery:8761/eureka
    links:
      - discovery
      - db_product_service
  gateway_service:
    build:
        dockerfile: gateway-DockerFile
    ports:
        - ${GATEWAY_SERVER_PORT}:8080
    environment:
      eureka.client.service-url.defaultZone: http://discovery:8761/eureka
    links:
      - discovery
      - product_service
      - order_service
  discovery:
    build:
      dockerfile: eureka-DockerFile
    ports:
      - ${EUREKA_SERVER_PORT}:8761