version: '3.3'
services:

  db_order_service:
    image: postgres:latest
    restart: always
    ports:
      - ${ORDER_POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${ORDER_POSTGRES_USER}
      - POSTGRES_PASSWORD=${ORDER_POSTGRES_PASSWORD}
      - POSTGRES_DB=${ORDER_POSTGRES_DB}
    depends_on:
      - discovery
  order_service:
    build:
      dockerfile: order-DockerFile
    ports:
      - 8081:8081
    depends_on:
      - db_order_service
      - discovery
    environment:
      ORDER_DATASOURCE_URL: jdbc:postgresql://db_order_service:5432/${ORDER_POSTGRES_DB}
      ORDER_DATASOURCE_USERNAME: ${ORDER_POSTGRES_USER}
      ORDER_DATASOURCE_PASSWORD: ${ORDER_POSTGRES_PASSWORD}
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: "http://172.19.0.2:8761/eureka"
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: "http://172.19.0.2:8761/eureka"
    links:
      - discovery
      - db_order_service
  discovery:
    build:
      dockerfile: eureka-DockerFile
    ports:
      - 8761:8761
    hostname: localhost