spring:
    application:
        name: product-service
    eureka:
        client:
            register-with-eureka: true
            fetch-registry: true
    datasource:
        url: ${PRODUCT_DATASOURCE_URL}
        username: ${PRODUCT_DATASOURCE_USERNAME}
        password: ${PRODUCT_DATASOURCE_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create
management:
    endpoints:
        web:
            exposure:
                include: health, info
    info:
        java:
            enabled: true
        os:
            enabled: true
server:
    port: 8082