spring:
    application:
        name: product-service
    eureka:
        client:
            register-with-eureka: true
            fetch-registry: true
management:
    endpoints:
        web:
            exposure:
                include: health, info
    info:
        java:
            enabled: true
        os:
            enabled: true
server:
    port: 8082