spring:
    application:
        name: order-service
    eureka:
        client:
            register-with-eureka: true
            fetch-registry: true
    datasource:
        url: ${ORDER_DATASOURCE_URL}
        username: ${ORDER_DATASOURCE_USERNAME}
        password: ${ORDER_DATASOURCE_PASSWORD}
        driver-class-name: org.postgresql.Driver
management:
    endpoints:
        web:
            exposure:
                include: health, info
    info:
        java:
            enabled: true
        os:
            enabled: true
server:
    port: 8081
