spring:
    application:
        name: gateway
    eureka:
        client:
            registerWithEureka: true
            fetchRegistry: true
            serviceUrl:
                defaultZone: http://eureka_server:8761/eureka
        instance:
            prefer-ip-address: true
            hostname: gateway
    cloud:
        gateway:
            mvc:
                routes:
                    -   id: order-service
                        uri: lb://order-service
                        predicates:
                            - Path=/orders/**
                    -   id: product-service
                        uri: lb://product-service
                        predicates:
                            - Path=/products/**
                    -   id: google-routing
                        uri: https://www.google.com
                        predicates:
                            - Path=/google/**
                        filters:
                            - StripPrefix=2
management:
    endpoints:
        web:
            exposure:
                include: health, info
    info:
        java:
            enabled: true
        os:
            enabled: true

logging:
    level:
        root: INFO