spring:
    application:
        name: eureka
    eureka:
        client:
            register-with-eureka: false
            fetch-registry: false
management:
    endpoints:
        web:
            exposure:
                include: health, info
    info:
        java:
            enabled: true
        os:
            enabled: true
server:
    port: 8761
logging:
    level:
        root: INFO


